### ISSUE TITLE
Cura plugin failure when trying to send file

### ISSUE THREAD

**Issue by Pilson66** [miblooming/JZ-TS24-2#33]
Today I updated the plugin for Cura 4.4.1 Linux.
Several problems at once:

Case 1. The plugin is not visible until replace the line:
![scr0126](https://user-images.githubusercontent.com/8355219/73661305-83512180-46a2-11ea-9050-385b3db29a3d.png)

Case 2. When go to the "ZJTSWIFI" plug-in tab, the Cura crashes until I comment out the following lines. And atfer that, I need to manually add IP address of my printer to JZ_TS_WIFIPlugin/res/MyMain.qml.
![scr0127](https://user-images.githubusercontent.com/8355219/73661438-beebeb80-46a2-11ea-8944-0a7661aba5dc.png)

Case 3. When I trying to send a file to the printer, the Cura crashes aiagin.

Screenshots:

For case 2:
`Traceback (most recent call last):
  File "/home/pilson/.local/share/cura/4.4/plugins/JZ_TS_WIFIPlugin/JzTsWifiStage.py", line 62, in init_jz_plugin
    self.plugin_main.init_stage(self.plugin_ui_item,self.upload_file_name)
  File "/home/pilson/.local/share/cura/4.4/plugins/JZ_TS_WIFIPlugin/PluginMain.py", line 365, in init_stage
    self.bind_ui()
  File "/home/pilson/.local/share/cura/4.4/plugins/JZ_TS_WIFIPlugin/PluginMain.py", line 405, in bind_ui
    self.update_history_ip()
  File "/home/pilson/.local/share/cura/4.4/plugins/JZ_TS_WIFIPlugin/PluginMain.py", line 313, in update_history_ip
    model.setItemData(model.createIndex(i,0), {1:self.ip_list[i],0:"True"})
RuntimeError: no access to protected functions or signals for objects not created from Python`

`Thread 0x00007fbb367fc700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb36ffd700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 549 in wait
  File "/tmp/.mount_curaB1CSdD/usr/bin/plugins/plugins/UM3NetworkPrinting/src/Network/ZeroConfClient.py", line 74 in _handleOnServiceChangedRequests
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb377fe700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb37fff700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb54bee700 (most recent call first):
  File "/tmp/.mount_curaB1CSdD/usr/bin/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 61 in _updateThread
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb553ef700 (most recent call first):
  File "/tmp/.mount_curaB1CSdD/usr/bin/plugins/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 86 in _updateThread
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb74ff9700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb757fa700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb75ffb700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb767fc700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb76ffd700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb777fe700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb77fff700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fbb848d3700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007fbb9e636740 (most recent call first):
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 306 in _logInfoWidget
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 156 in _createDialog
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 77 in __init__
  File "/build/4.4/build/inst/bin/cura", line 111 in exceptHook
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 341 in exec_
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 804 in run
  File "/build/4.4/build/inst/bin/cura", line 180 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
  File "/build/env/4.4/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
  File "/build/env/4.4/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
`

For Case 3:
![scr0125](https://user-images.githubusercontent.com/8355219/73660787-8ef01880-46a1-11ea-871b-3ae8002bcd91.png)

**Comment by miblooming** [comment]
I only test it on Windows.
So there maybe some bugs on Mac and Linux.
I'll fix it Later.

**Comment by Super-Matter** [comment]
Have the same problem on Windows 10.

**Comment by miblooming** [comment]
Please use WifiHelper temporarily.
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/WifiHelper

I'll fix the cura plugin.

**Comment by Pilson66** [comment]
Any news?

**Comment by miblooming** [comment]
not yet
